FROM apache/spark:3.5.3

USER root

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends python3 python3-pip; \
    ln -sf /usr/bin/python3 /usr/bin/python; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

ENV PYSPARK_PYTHON=/usr/bin/python3
ENV PYSPARK_DRIVER_PYTHON=/usr/bin/python3
